version: '3.9'

services:
    app:
        build:
            dockerfile: .docker/Dockerfile
            network: default
            context: .
        container_name: kefirium
        restart: always
        user: www-data
        ports:
            - "80:80"
        networks:
            - default
        depends_on:
            db:
                condition: service_healthy
        links:
            -   db

    db:
        image: postgres
        restart: always
        networks:
            - default
        ports:
            - "54320:5432"
        healthcheck:
           test: [ "CMD-SHELL", "pg_isready" ]
           interval: 10s
           timeout: 5s
           retries: 5
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: admin
        volumes:
            - ./.local-pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - "5050:80"
        networks:
            - default
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@mail.ru
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - ./.pgadmin-data:/var/lib/pgadmin
        depends_on:
            db:
                condition: service_healthy

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./.redis-data:/root/redis
        environment:
            - REDIS_PASSWORD=my-password
            - REDIS_PORT=6379
            - REDIS_DATABASES=2
        networks:
            - default
